import { characters } from "../../../types/Types";

export const charactersCarousel: characters[] = [
  {
    id: 1,
    name: "Isaac",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "/img/characters/isaac/isaac_c.png",
  },
  {
    id: 2,
    name: "Magdalene",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "/img/characters/magdalene/magdalene_c.png",
  },
  {
    id: 3,
    name: "Cain",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "/img/characters/cain/cain_c.png",
  },
  {
    id: 4,
    name: "Judas",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "/img/characters/judas/judas_c.png",
  },
  {
    id: 5,
    name: "???",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "/img/characters/blue_baby/blue_baby_c.png",
  },
  {
    id: 6,
    name: "Eve",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 7,
    name: "Samson",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 8,
    name: "Azazel",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 9,
    name: "Lazarus",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 10,
    name: "Eden",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 11,
    name: "The Lost",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 12,
    name: "Lilith",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 13,
    name: "Keeper",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 14,
    name: "Apollyon",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 15,
    name: "The Forgotten",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 16,
    name: "Bethany",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
  {
    id: 17,
    name: "Jacob & Esau",
    name_img: "",
    characterPixel_img: "",
    characterCard_img: "",
  },
];
