import { PixelSpriteBg, PixelStatic, ShadowSprite } from "../../../types/Types";

const shadow_character: ShadowSprite = {
  width: 5,
  height: 2,
  shadow_img: "/img/shadows/pixel/shadow_character.png",
  bottom: -7,
  animation: [0, 18],
  sprites: 2,
};

const shadow_running_bottom: ShadowSprite = {
  width: 5,
  height: 2,
  shadow_img: "/img/shadows/pixel/shadow_character.png",
  bottom: -4,
  animation: [0, 15],
  sprites: 2,
};

const shadow_spider: ShadowSprite = {
  width: 3,
  height: 1.5,
  shadow_img: "/img/shadows/pixel/shadow_enemies.png",
  bottom: -10,
  animation: [0, 19],
  sprites: 3,
};

const shadow_bat: ShadowSprite = {
  width: 5,
  height: 2,
  shadow_img: "/img/shadows/pixel/shadow_enemies.png",
  bottom: -16,
  animation: [2, 20],
  sprites: 3,
};

const shadow_fly: ShadowSprite = {
  width: 3,
  height: 1.5,
  shadow_img: "/img/shadows/pixel/shadow_enemies.png",
  bottom: -40,
  left: -7,
  animation: [0, 10],
  sprites: 3,
};

const shadow_charger_back: ShadowSprite = {
  width: 5,
  height: 2,
  shadow_img: "/img/shadows/pixel/shadow_enemies.png",
  bottom: 19,
  left: -15,
  animation: [0, 16],
  sprites: 3,
};

const shadow_poop: ShadowSprite = {
  width: 4.4,
  height: 2,
  shadow_img: "/img/shadows/pixel/shadow_enemies.png",
  bottom: -15,
  animation: [0, 15],
  sprites: 3,
};

export const pixelSprite2: PixelSpriteBg[] = [
  {
    width: 10,
    height: 9,
    background_img: "/img/monsters/baby_long_legs.png",
    animation: [0, 30],
    bottom: 20,
    right: 65,
    x: 50,
    y: -50,
    sprites: 5,
    shadow: shadow_spider,
  },
  {
    width: 10,
    height: 9,
    background_img: "/img/monsters/crazy_long_legs.png",
    animation: [3, 30],
    bottom: 52,
    right: 14,
    x: -80,
    y: -80,
    sprites: 5,
    shadow: shadow_spider,
  },
  {
    width: 6.5,
    height: 8,
    background_img: "/img/monsters/gaper.png",
    animation: [2, 22],
    bottom: 45.5,
    left: 12,
    x: 100,
    sprites: 10,
    scaleX: -1,
    shadow: shadow_character,
  },
  {
    width: 6.5,
    height: 10,
    background_img: "/img/others/isaac_running.png",
    animation: [0, 20],
    bottom: 45,
    right: 40,
    x: -90,
    sprites: 10,
    shadow: shadow_character,
  },
];

export const pixelSprite3: PixelSpriteBg[] = [
  {
    width: 8.5,
    height: 9,
    background_img: "/img/obstacles/fire_place.png",
    animation: [0, 25],
    top: 8.4,
    right: 15.7,
    sprites: 6,
  },
  {
    width: 8.5,
    height: 9,
    background_img: "/img/obstacles/fire_place.png",
    animation: [3, 28],
    bottom: 11.4,
    left: 16.7,
    sprites: 6,
  },
  {
    width: 11,
    height: 7.5,
    background_img: "/img/monsters/one_tooth.png",
    animation: [0, 26],
    top: 20,
    left: 30,
    x: -40,
    y: 120,
    sprites: 3,
    shadow: shadow_bat,
  },
  {
    width: 11,
    height: 8.5,
    background_img: "/img/monsters/fat_bat.png",
    animation: [0, 26],
    bottom: 18,
    left: 28,
    x: 50,
    y: -80,
    sprites: 3,
    shadow: shadow_bat,
  },
  {
    width: 7,
    height: 3.2,
    background_img: "/img/monsters/charger.png",
    animation: [0, 28],
    top: 13,
    left: 43,
    x: 130,
    sprites: 4,
    shadow: shadow_character,
  },
  {
    width: 11,
    height: 7.5,
    background_img: "/img/monsters/one_tooth_angry.png",
    animation: [2, 26],
    top: 32,
    right: 40,
    x: 45,
    y: 130,
    sprites: 3,
    shadow: shadow_bat,
  },
  {
    width: 4,
    height: 5.5,
    background_img: "/img/monsters/charger_back.png",
    animation: [2, 26],
    bottom: 25,
    left: 13,
    y: -160,
    sprites: 4,
    shadow: shadow_charger_back,
  },
  {
    width: 4,
    height: 5.5,
    background_img: "/img/monsters/charger_front.png",
    animation: [2, 26],
    bottom: 50,
    right: 13,
    y: 250,
    sprites: 4,
    shadow: shadow_charger_back,
  },
  {
    width: 7,
    height: 8.1,
    background_img: "/img/characters/eve/eve_front.png",
    animation: [0, 20],
    top: 38,
    right: 25,
    y: 180,
    sprites: 10,
    shadow: shadow_running_bottom,
  },
];

export const pixelSprite4: PixelSpriteBg[] = [
  {
    width: 5,
    height: 6.9,
    background_img: "/img/monsters/blind_creep_wall_lr.png",
    animation: [0, 15],
    top: 40,
    right: 7,
    sprites: 4,
    y: 86,
  },
  {
    width: 6.9,
    height: 5,
    background_img: "/img/monsters/wall_creep.png",
    animation: [2, 17],
    top: 10.5,
    left: 38,
    sprites: 4,
    x: -78,
  },
  {
    width: 4.4,
    height: 4.8,
    background_img: "/img/monsters/dip.png",
    animation: [0, 10],
    bottom: 28.5,
    right: 24.5,
    sprites: 3,
    x: 50,
    y: -100,
    shadow: shadow_poop,
  },
  {
    width: 6.5,
    height: 8,
    background_img: "/img/monsters/boney.png",
    animation: [0, 11],
    top: 33.5,
    left: 17.5,
    sprites: 10,
    y: 70,
    shadow: shadow_running_bottom,
  },
  {
    width: 4.5,
    height: 5,
    background_img: "/img/monsters/sucker.png",
    animation: [0, 12],
    bottom: 24,
    left: 20,
    sprites: 2,
    y: -25,
    x: 45,
    shadow: shadow_fly,
  },
  {
    width: 4.5,
    height: 5,
    background_img: "/img/monsters/pooter.png",
    animation: [1, 14],
    top: 21.5,
    right: 24,
    sprites: 2,
    y: -20,
    x: -20,
    scaleX: -1,
    shadow: shadow_fly,
  },
];

export const pixelSpritesBg4: PixelStatic[] = [
  {
    width: 6,
    height: 6,
    img: "/img/obstacles/web.png",
    top: 18,
    right: 23.5,
    scaleX: -1,
  },
  {
    width: 6,
    height: 6,
    img: "/img/obstacles/web2.png",
    bottom: 18.6,
    left: 23.9,
  },
  {
    width: 6,
    height: 6,
    img: "/img/obstacles/web.png",
    top: 27.5,
    left: 12,
  },
  {
    width: 6,
    height: 6,
    img: "/img/obstacles/web2.png",
    bottom: 27.3,
    right: 11.6,
  },
  {
    width: 6,
    height: 6,
    img: "/img/obstacles/web.png",
    top: 36.5,
    right: 11.6,
  },
  {
    width: 6,
    height: 6,
    img: "/img/obstacles/web.png",
    bottom: 27.8,
    left: 18,
  },
  {
    width: 7.2,
    height: 7.2,
    img: "/img/obstacles/black_poop.png",
    bottom: 26.4,
    left: 11.1,
  },
  {
    width: 7.2,
    height: 7.2,
    img: "/img/obstacles/black_poop.png",
    top: 26.5,
    right: 11.35,
  },
];

export const pixelSprite5: PixelSpriteBg[] = [
  {
    width: 6.5,
    height: 10,
    background_img: "/img/others/lazarus_running.png",
    animation: [0, 18],
    top: 39,
    right: 25,
    sprites: 10,
    x: -150,
    shadow: shadow_character,
  },
  {
    width: 8.5,
    height: 9,
    background_img: "/img/obstacles/fire_place.png",
    animation: [0, 18],
    top: 11,
    right: 10,
    sprites: 6,
  },
  {
    width: 8.5,
    height: 9,
    background_img: "/img/obstacles/fire_place.png",
    animation: [3, 22],
    bottom: 18,
    right: 10,
    sprites: 6,
  },
  {
    width: 4.5,
    height: 9,
    background_img: "/img/monsters/mask/mask_running_side.png",
    animation: [0, 0],
    top: 9,
    right: 48,
    sprites: 1,
    scaleX: -1,
    x: 100,
    shadow: {
      width: 4.3,
      height: 1.8,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -18,
      left: -5,
      animation: [0, 15],
      sprites: 3,
    },
  },
  {
    width: 6,
    height: 9,
    background_img: "/img/monsters/heart/heart.png",
    animation: [0, 21],
    bottom: 48,
    left: 35,
    sprites: 8,
    y: -100,
    shadow: {
      width: 4.6,
      height: 1.9,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -17,
      left: 9,
      animation: [3, 19],
      sprites: 3,
    },
  },
  {
    width: 6.5,
    height: 10,
    background_img: "/img/monsters/gazin_globin/gazing_globin.png",
    animation: [1, 24],
    bottom: 21,
    left: 33,
    sprites: 10,
    x: 120,
    scaleX: -1,
    shadow: shadow_character,
  },
  {
    width: 6.5,
    height: 10,
    background_img: "/img/monsters/deaths_head/deaths_head.png",
    animation: [0, 16],
    top: 10,
    right: 22,
    sprites: 4,
    x: 110,
    y: 80,
    shadow: {
      width: 4.5,
      height: 1.8,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -18,
      left: 0,
      animation: [0, 15],
      sprites: 3,
    },
  },
  {
    width: 5,
    height: 6.9,
    background_img: "/img/monsters/rage_creep/rage_creep_side.png",
    animation: [0, 16],
    bottom: 25,
    left: 7,
    sprites: 4,
    scaleX: -1,
    scaleY: -1,
    y: -90,
  },
  {
    width: 7,
    height: 8.1,
    background_img: "/img/monsters/globin/globin.png",
    animation: [1, 24],
    bottom: 52,
    left: 17.5,
    sprites: 10,
    y: 100,
    shadow: shadow_running_bottom,
  },
];

export const pixelSprite6: PixelSpriteBg[] = [
  {
    width: 7.2,
    height: 7.2,
    background_img: "/img/monsters/guts/guts.png",
    animation: [2, 38],
    sprites: 12,
    top: 10.2,
    left: 60,
    x: -480,
  },
  {
    width: 7.2,
    height: 7.2,
    background_img: "/img/monsters/guts/guts.png",
    animation: [0, 35],
    sprites: 12,
    top: 43.8,
    left: 13,
    x: 480,
    scaleX: -1,
  },
  {
    width: 7.2,
    height: 7.2,
    background_img: "/img/monsters/guts/guts.png",
    animation: [0, 37],
    sprites: 12,
    bottom: 10.8,
    right: 6.3,
    y: -500,
    scaleX: -1,
  },
  {
    width: 7,
    height: 7,
    background_img: "/img/monsters/host/host.png",
    animation: [0, 0],
    sprites: 1,
    top: 20.8,
    left: 13.2,
  },
  {
    width: 7,
    height: 7,
    background_img: "/img/monsters/host/host.png",
    animation: [0, 0],
    sprites: 1,
    top: 32,
    left: 13.2,
  },
  {
    width: 6.5,
    height: 5,
    background_img: "/img/monsters/leech/leech.png",
    animation: [0, 33],
    top: 36,
    left: 57,
    x: -490,
    sprites: 6,
    scaleX: -1,
    shadow: {
      width: 4,
      height: 1.6,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -19,
      left: 0,
      animation: [0, 15],
      sprites: 3,
    },
  },
  {
    width: 6,
    height: 6.6,
    background_img: "/img/monsters/boomfly/boomfly.png",
    animation: [0, 34],
    right: 45,
    bottom: 4,
    y: -220,
    x: 220,
    sprites: 2,
    scaleX: -1,
    shadow: {
      width: 4,
      height: 1.6,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -19,
      left: 0,
      animation: [0, 23],
      sprites: 3,
    },
  },
  {
    width: 6,
    height: 6.6,
    background_img: "/img/monsters/boomfly/boomfly.png",
    animation: [0, 33],
    top: 8,
    right: 26,
    y: 250,
    x: 250,
    sprites: 2,
    scaleX: -1,
    shadow: {
      width: 4,
      height: 1.6,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -19,
      left: 0,
      animation: [0, 20],
      sprites: 3,
    },
  },
  {
    width: 6,
    height: 6.6,
    background_img: "/img/monsters/boomfly/boomfly.png",
    animation: [0, 33],
    top: 20,
    left: 7,
    y: -280,
    x: 300,
    sprites: 2,
    scaleX: -1,
    shadow: {
      width: 4,
      height: 1.6,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: -19,
      left: 0,
      animation: [0, 25],
      sprites: 3,
    },
  },
  {
    width: 6,
    height: 6.6,
    background_img: "/img/monsters/vis/vis.png",
    animation: [0, 30],
    top: 22,
    right: 50,
    x: 350,
    sprites: 8,
    shadow: shadow_character,
  },
  {
    width: 6.5,
    height: 6.5,
    background_img: "/img/monsters/leech/leech_bottom.png",
    animation: [0, 33],
    top: 36,
    right: 18.5,
    y: 380,
    sprites: 6,
    shadow: {
      width: 4,
      height: 1.6,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: 16,
      left: 0,
      animation: [0, 15],
      sprites: 3,
    },
  },
  {
    width: 11,
    height: 10,
    background_img: "/img/others/samsom_run_6.png",
    animation: [0, 25],
    top: 48,
    right: 17,
    y: 230,
    sprites: 10,
    shadow: shadow_running_bottom,
  },
  {
    width: 11,
    height: 10,
    background_img: "/img/others/judas_run_6.png",
    animation: [0, 26],
    top: 33,
    left: 23,
    x: 230,
    sprites: 10,
    scaleX: -1,
    shadow: shadow_running_bottom,
  },
  {
    width: 11,
    height: 10,
    background_img: "/img/others/bethany_run_6.png",
    animation: [0, 26],
    bottom: 14,
    right: 30,
    y: -300,
    sprites: 10,
    shadow: shadow_running_bottom,
  },
  {
    width: 11,
    height: 10,
    background_img: "/img/others/magdalene_run_6.png",
    animation: [0, 25],
    top: 28,
    right: 20,
    x: -180,
    sprites: 10,
    shadow: shadow_running_bottom,
  },
];

export const pixelSprite7: PixelSpriteBg[] = [
  {
    width: 22,
    height: 38,
    background_img: "/img/Bosses/moms_heart_its_lives/moms_heart_its_lives.png",
    animation: [2, 45],
    top: 0,
    right: 39,
    sprites: 5,
    shadow: {
      width: 11,
      height: 4.6,
      shadow_img: "/img/shadows/pixel/shadow_enemies.png",
      bottom: 12,
      left: -4,
      animation: [0, 30],
      sprites: 3,
    },
  },
  {
    width: 27,
    height: 12,
    background_img:
      "/img/Bosses/moms_heart_its_lives/moms_heart_its_lives_left.png",
    animation: [0, 0],
    top: 0,
    left: 15,
    sprites: 1,
  },
  {
    width: 28,
    height: 10.5,
    background_img:
      "/img/Bosses/moms_heart_its_lives/moms_heart_its_lives_right.png",
    animation: [0, 0],
    top: 0,
    right: 16,
    sprites: 1,
  },
];
